name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      GO111MODULE: on
      TARGET: amd64
        
    strategy:
#       max-parallel: 2
      matrix:
        go-version: [1.13.x]
        os: [ubuntu-18.04, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Checkout project  
      uses: actions/checkout@v2
      
    - name: Clone API project
      run: go get github.com/sodafoundation/api
      
    - name: Install Pre-requisites
      run: sudo apt-get update && sudo apt-get install -y git make curl wget libltdl7 libseccomp2 libffi-dev gawk build-essential gcc librados-dev librbd-dev
      
    - name: Build
      # Build SODA Dock source code
      run: make all 

    - name: Run CI scripts for Testing
      run: ./install/CI/coverage && ./install/CI/test
    
    - name: After success run Codecov Coverage tool.
      run: bash <(curl -s https://codecov.io/bash)
